version: '3'
services:
  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    volumes:
      - /data/docker/nginx/conf:/etc/nginx
      - /data/docker/nginx/html:/usr/share/nginx/html
      - /data/docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
  redis:
    image: redis:7.0.12
    container_name: redis
    command: redis-server
    restart: always
    volumes:
      - /data/docker/redis/data:/data
    ports:
      - 6379:6379
  sbs-front:
    image: deepraining/sbs-front:2025.0101.0101
    container_name: sbs-front
    restart: always
    volumes:
      - /data/app/sbs-front/logs:/var/logs
      - /etc/localtime:/etc/localtime
    ports:
      - 18001:18001
